version: '3.9'

services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Eventy.Api
    build:
      context: .
      dockerfile: Evently.Api/Dockerfile
    ports:
      - 5000:8000
      - 5001:8081
  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/db:/var/lib/postgressql/data
    ports:
      - "5432:5432"

