version: '3.9'

services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Eventy.Api
    build:
      context: .
      dockerfile: Evently.Api/Dockerfile
    ports:
      - 5000:8000
      - 5001:8081
  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/db:/var/lib/postgressql/data
    ports:
      - "5432:5432"
  evently.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Evently.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
      - 8080:80
  evently.redis:
    image: redis:latest
    restart: always
    container_name: Evently.Redis
    ports:
      - "6379:6379" 
    

